In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "../data/processed/cleaned_marketing_data.csv"
)

df["DATE_DAY"] = pd.to_datetime(df["DATE_DAY"])

In [2]:
# Create Log Revenue
df["LOG_REVENUE"] = np.log1p(
    df["ALL_PURCHASES_ORIGINAL_PRICE"]
)

In [3]:
# Create Total Clicks 

click_cols = [
    "GOOGLE_PAID_SEARCH_CLICKS",
    "GOOGLE_SHOPPING_CLICKS",
    "GOOGLE_PMAX_CLICKS",
    "GOOGLE_DISPLAY_CLICKS",
    "GOOGLE_VIDEO_CLICKS",
    "META_FACEBOOK_CLICKS",
    "META_INSTAGRAM_CLICKS",
    "META_OTHER_CLICKS",
    "TIKTOK_CLICKS"
]

df[click_cols] = df[click_cols].fillna(0)

df["TOTAL_CLICKS"] = df[
    click_cols
].sum(axis=1)

In [5]:
# Create Impression

imp_cols = [
    "GOOGLE_PAID_SEARCH_IMPRESSIONS",
    "GOOGLE_SHOPPING_IMPRESSIONS",
    "GOOGLE_PMAX_IMPRESSIONS",
    "GOOGLE_DISPLAY_IMPRESSIONS",
    "GOOGLE_VIDEO_IMPRESSIONS",
    "META_FACEBOOK_IMPRESSIONS",
    "META_INSTAGRAM_IMPRESSIONS",
    "META_OTHER_IMPRESSIONS",
    "TIKTOK_IMPRESSIONS"
]

df[imp_cols] = df[imp_cols].fillna(0)

df["TOTAL_IMPRESSIONS"] = df[
    imp_cols
].sum(axis=1)

In [6]:
# Create ctr
df["CTR"] = (
    df["TOTAL_CLICKS"]
    /
    (df["TOTAL_IMPRESSIONS"] + 1)
)

In [7]:
# Create Total Purchase

df["TOTAL_PURCHASES"] = (
    df["ALL_PURCHASES"]
)

In [13]:
# Create ROAS (Return on Ad Spend)
df["ROAS"] = np.where(
    df["TOTAL_MARKETING_SPEND"] > 0,
    df["ALL_PURCHASES_ORIGINAL_PRICE"] /
    df["TOTAL_MARKETING_SPEND"],
    np.nan
)

In [14]:
df["ROAS"].describe()

count    1.278890e+05
mean     2.675363e+02
std      4.564481e+04
min      2.684031e-02
25%      4.426091e+00
50%      1.090698e+01
75%      2.612628e+01
max      1.597716e+07
Name: ROAS, dtype: float64

In [9]:
# Create Digit Spend
df["DIGITAL_SPEND"] = (
      df["GOOGLE_PAID_SEARCH_SPEND"]
    + df["GOOGLE_SHOPPING_SPEND"]
    + df["GOOGLE_PMAX_SPEND"]
    + df["GOOGLE_DISPLAY_SPEND"]
    + df["GOOGLE_VIDEO_SPEND"]
    + df["META_FACEBOOK_SPEND"]
    + df["META_INSTAGRAM_SPEND"]
    + df["META_OTHER_SPEND"]
    + df["TIKTOK_SPEND"]
)

In [16]:
# Checking Features
features = [
    "TOTAL_MARKETING_SPEND",
    "TOTAL_CLICKS",
    "TOTAL_IMPRESSIONS",
    "CTR",
    "ROAS",
    "DIGITAL_SPEND",
    "LOG_REVENUE"
]

df[features].head()

,TOTAL_MARKETING_SPEND,TOTAL_CLICKS,TOTAL_IMPRESSIONS,CTR,ROAS,DIGITAL_SPEND,LOG_REVENUE
0,439.278905,418.0,50904.0,0.008211,10.364678,439.278905,8.423758
1,525.922025,476.0,64671.0,0.007360,6.042717,525.922025,8.064321
2,701.946429,553.0,82891.0,0.006671,7.791191,701.946429,8.607034
3,652.532798,531.0,81525.0,0.006513,5.112341,652.532798,8.112819
4,610.972971,503.0,71244.0,0.007060,6.533820,610.972971,8.292295

In [17]:
df.to_csv(
    "../data/processed/featured_marketing_data.csv",
    index=False
)

In [18]:
df[features].describe()

,TOTAL_MARKETING_SPEND,TOTAL_CLICKS,TOTAL_IMPRESSIONS,CTR,ROAS,DIGITAL_SPEND,LOG_REVENUE
count,1.327590e+05,132759.000000,1.327590e+05,132759.000000,1.278890e+05,1.327590e+05,132759.000000
mean,9.107843e+03,2467.950881,2.168598e+05,0.014115,2.675363e+02,9.107843e+03,9.000782
std,1.054895e+05,3851.662905,3.330895e+05,0.023524,4.564481e+04,1.054895e+05,1.660847
min,0.000000e+00,0.000000,0.000000e+00,0.000000,2.684031e-02,0.000000e+00,1.501853
25%,2.257300e+02,348.000000,3.176800e+04,0.007333,4.426091e+00,2.257300e+02,7.842671
50%,7.069470e+02,970.000000,8.519300e+04,0.010634,1.090698e+01,7.069470e+02,8.928375
75%,1.937101e+03,2848.000000,2.460050e+05,0.015636,2.612628e+01,1.937101e+03,10.051716
max,8.813257e+06,70438.000000,1.401180e+07,0.710938,1.597716e+07,8.813257e+06,18.689864